behaviors:
  Hider:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 65536
      learning_rate: 0.0003
      beta: 0.003
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.05
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
